{% set name = "veusz" %}
{% set version = "3.6.2" %}
{% set sha256 = "c2171ac45e4b30424d8fc35261e2e99dbe6e25ba1197ebc24355b106b26395d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win and vc<14]
  entry_points:
    - veusz = veusz.veusz_main:run
  osx_is_app: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - python
    - pip
    - setuptools
    - qt-main
    - pyqt
    - pyqt5-sip
    - numpy
    - tomli
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt-main
    - pyqt
    - {{ pin_compatible('numpy') }}
    - setuptools

test:
  imports:
    - veusz
    - veusz.helpers.qtloops # separate import to check C extensions
  commands:
    - veusz -platform minimal --help

app:
  entry: veusz
  icon: veusz_64.png
  summary: Veusz 2D and 3D interactive scientific plotting
  type: desk

about:
  home: https://veusz.github.io/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 2D and 3D interactive scientific plotting GUI and module

  description: |
    Veusz is a 2D and 3D scientific plotting package, designed to
    create publication-ready PDF and SVG output. It features GUI,
    command-line, and scripting interfaces. Graphs are constructed
    from widgets, allowing complex layouts to be designed. Veusz
    supports plotting functions, data with errors, keys, labels,
    stacked plots, multiple plots, and fitting data.
  doc_url: https://veusz.github.io/help-support/
  dev_url: https://veusz.github.io/development/

extra:
  recipe-maintainers:
    - jeremysanders
