appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QY5v/PXyVgBqdQODGh7gZuYnTkKLaxy0RY9s14snQSw7Tmjbv7QYwXVOmWNnnTioX0MgPxTd0nJkdjUSClKyk2QlApbg2zvg5pIn4e19iR9w/DU0N9zI0clchP7ZXtl3zRE5zOpe4FsvYH/PK3JoecDppLm2BYHW6MKYiIAveZJ6aIhxwsxoeh9HKtix7y/OiNVSNubM0HQC4ACXdpQFZ4tTiECjKd7BepI5hIKe+HDDWKRsx5TDkPQLePRZjEuFfyFS7K4aE6Xm16KRoJdqgyszLAeWEF/+0MJ+AvieGv9vx5kPHUXqXLnV1ppIUpj9rczxCtpMIO9I9ghttxCuFydQ9+FUlxNHBd4EURoBy6a6KlUv9n3kgQiYTJLpoCM1ubtDOpGaKUae1eUYP7Kbftwl+uhfWR4GPlGjYvByZ185kCftfI5iy3xK7gNYRMFNKEijPo3yvYNg0Ds3qNLDPOtvT588pBulXbfF6r8FT3eT2MU5Q6bzeyy44HGdZ/hyR+DLdpCellZt45PzfESSQb0fkFEZZlrqMKrMCu5aZohk4iWbySazUXHt3aFe6YDtwfDZQDQlkJxsYnoChWsnpzr9LWWpJ8SR/jxVDIdBxo23A8XFvbkGL12xdwjNGqYz7K5sqklXMZWC8m4nii8F0lIdQPSTev7Tx0WGXJp5ULY=}
